### ISSUE TITLE
what is this error?

### ISSUE THREAD

**Issue by zhenhang66** [npr99/URSC645#5]
<istmt>:  3499  _st__put_cmd_clear() not found

tried to run
PRJ-2769_archive\PRJ-2769\02_ReportTablesFigures

**Comment by npr99** [comment]
https://www.stata.com/statalist/archive/2011-04/msg00185.html

This is a result of an incomplete update.

Try to run these lines of code in Stata:
```
update executable, force
update utilities, force
```

**Comment by npr99** [comment]
https://www.statalist.org/forums/forum/general-stata-discussion/general/1430643-error-r-3499

another link that I found when I googled the error.
I Googled "3499 _st__put_cmd_clear() not found stata"
